### ISSUE TITLE
复现FEVER-->AntiVax ba=0.51524

### ISSUE THREAD

**Issue by zoeChen119** [Yueeeeeeee/MetaAdapt#2]
![image](https://github.com/Yueeeeeeee/MetaAdapt/assets/35884699/e1dacb14-6f3e-4222-bacf-ece8e3bfec6d)
AntiVax-dataset.csv
![image](https://github.com/Yueeeeeeee/MetaAdapt/assets/35884699/6a1955e5-8b6a-43a7-8b08-314508798a0b)
FEVER-test.jsonl
![image](https://github.com/Yueeeeeeee/MetaAdapt/assets/35884699/907ac6c7-0d31-404e-bc7e-3c9607614066)
config.py(没有修改）
![image](https://github.com/Yueeeeeeee/MetaAdapt/assets/35884699/e688875b-695e-4add-a7e3-2ad517937fb9)

不知道是不是哪里没弄好

**Comment by Yueeeeeeee** [comment]
Have you downloaded the text data in AntiVax from Twitter? It seems you only have IDs in your AntiVax-dataset.csv

**Comment by zoeChen119** [comment]
Can you share its Twitter link？:)

**Comment by Yueeeeeeee** [comment]
You should register for the twitter API and download the text via the provided API. See https://developer.twitter.com/en/products/twitter-api
