### ISSUE TITLE
关于论文，我想问在定义损失函数的时候，为什么是参数θ和少样本集去做交叉熵？据我所知这两个并不是同类数据。

### ISSUE THREAD

**Issue by SinyWu0615** [Yueeeeeeee/MetaAdapt#3]

**Comment by Yueeeeeeee** [comment]
这里的notation可能跟你理解有点不一样，实际上我们算CE还是用(x, y)，但是优化的对象是θ。举个例子，MetaAdapt的公式1实际上与下面的公式是等价的(注意f和θ都代表模型)
<img width="280" alt="截屏2023-11-03 下午1 42 42" src="https://github.com/Yueeeeeeee/MetaAdapt/assets/40675493/2fb9cf01-abb1-4926-b611-78fbbfdc2686">

**Comment by SinyWu0615** [comment]
我已收到您的邮件，会尽快处理，祝您生活愉快！

**Comment by SinyWu0615** [comment]
感谢您的详细解答，现在我能推导出您论文中的所有公式。另外，我想请问是否可以分享一下FakeNewsNet数据集，我去看了下数据集的仓库，发现需要twitter的api，但是我之前申请的api被拒绝了，想请问是否可以将您的数据集压缩打包发我一份？十分感谢！




761299486
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yueeeeeeee/MetaAdapt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 凌晨2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yueeeeeeee/MetaAdapt] 关于论文，我想问在定义损失函数的时候，为什么是参数θ和少样本集去做交叉熵？据我所知这两个并不是同类数据。 (Issue #3)





 
这里的notation可能跟你理解有点不一样，实际上我们算CE还是用(x, y)，但是优化的对象是θ。举个例子，MetaAdapt的公式1实际上与下面的公式是等价的(注意f和θ都代表模型)

**Comment by Yueeeeeeee** [comment]
你好 请从这个链接下载: https://drive.google.com/file/d/1m5yP-f-L-7hTA061tUTG4R69NrxTvvDL/view?usp=sharing
