### ISSUE TITLE
No such file or directory: './data/FakeNewsNet/fakenewsnet_dataset/gossipcop_0.1_0.2_split.json'

### ISSUE THREAD

**Issue by DimPenCHEN** [Yueeeeeeee/MetaAdapt#4]
![3cc5efc0a23e59c86e307dc8249308a](https://github.com/Yueeeeeeee/MetaAdapt/assets/120781027/999c386c-5358-4000-9ecf-346e0bb9f542)
It appears that I am unable to generate or locate the file that is supposed to be created based on the proportions of the test and validation sets. The file is intended to be created using val_size = 0.1 and test_size = 0.2, but I cannot find it or generate it. Is there an issue with my code causing this problem?

I hope I can get some assistance from you, by offering information and code snippets related to this file.Your help in this matter is greatly appreciated!

BTW , I found that the "os.listdir()" function made some mistake(it mixes the '/' and '\\' in path ) so that I remove it from wherever it exits, if this step occurs to json file can't be found I will correct my operation.

hoping for your early reply!
best wishes!

**Comment by Yueeeeeeee** [comment]
Hi, I think this might be a windows related issue. Please check the make_train_val_test_split function and make sure the json file is saved at the desired location.
